// <auto-generated />
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;

namespace LightMock.Generator
{
    [ExcludeFromCodeCoverage]
    public static class ContextResolver
    {
        public static LambdaExpression ExchangeForExpression(string token)
        {
            switch (token)
            {
                /*exchangeForExpressionBuilder*/
                default:
                    throw new ArgumentException($"expression for provided token [{token}] is not found");
            }
        }
    }

}
