// <auto-generated />
using System;
using System.Diagnostics.CodeAnalysis;

namespace LightMock.Generator
{
    [ExcludeFromCodeCoverage]
    public sealed class Mock<T> : AbstractMock<T>
        where T : class
    {

        public Mock()
            : base(Array.Empty<object>())
        { }

        public Mock(params object[] prms)
            : base(prms)
        { }
    }
}
