// <auto-generated />
using System;
using System.Linq.Expressions;

namespace LightMock.Generator
{
    public sealed class Mock<T> : AbstractMock<T>
        where T : class
    {

        public Mock() { }

        public Mock(params object[] prms)
            : base(prms)
        { }

        protected override Type GetInstanceType() => ContextResolver.GetInstanceType(typeof(T));
        protected override Type GetProtectedContextType() => ContextResolver.GetProtectedContextType(typeof(T));
        protected override Type GetPropertiesContextType() => ContextResolver.GetPropertiesContextType(typeof(T));
        protected override Type GetAssertType() => ContextResolver.GetAssertType(typeof(T));
        protected override T GetDelegate(Type type) => (T)ContextResolver.GetDelegate(type, PublicContext);
        protected override LambdaExpression ExchangeForExpression(string token)
            => ContextResolver.ExchangeForExpression(token);
    }
}
