using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace StaticProxy
{
    [Generator]
    public class StaticProxyGenerator : ISourceGenerator
    {
        const string KAttributeName = nameof(GenerateMockAttribute);
        const string KAttributeFile = KAttributeName + ".cs";

        readonly Lazy<string> attribute = new Lazy<string>(() => Utils.LoadResource(KAttributeFile));

        private static readonly SymbolDisplayFormat KNamespaceDisplayFormat = new SymbolDisplayFormat(
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces
            );


        public StaticProxyGenerator()
        {
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (context.Compilation is CSharpCompilation compilation &&
                context.SyntaxReceiver is StaticProxySyntaxReceiver receiver &&
                compilation.SyntaxTrees.First().Options is CSharpParseOptions options)
            {
                context.AddSource(KAttributeName, SourceText.From(attribute.Value, Encoding.UTF8));

                compilation = compilation
                    .AddReferences(MetadataReference.CreateFromFile(typeof(LightMock.InvocationInfo).Assembly.Location))
                    .AddSyntaxTrees(CSharpSyntaxTree.ParseText(SourceText.From(attribute.Value, Encoding.UTF8), options));

                var attributeSymbol = compilation.GetTypeByMetadataName(KAttributeName);
                if (attributeSymbol == null)
                {
                    context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticsDescriptors.KNoAttributeErrorDescriptor, Location.None, KAttributeName));
                    return;
                }

                foreach (var candidateClass in receiver.CandidateClasses)
                {
                    var model = compilation.GetSemanticModel(candidateClass.SyntaxTree);
                    var typeSymbol = model.GetDeclaredSymbol(candidateClass);
                    if (typeSymbol == null)
                        continue;
                    var relevantAttribute = typeSymbol.GetAttributes().FirstOrDefault(
                        a => attributeSymbol.Equals(a.AttributeClass, SymbolEqualityComparer.Default));
                    if (relevantAttribute == null)
                        continue;

                    var isPartial = candidateClass
                        .Modifiers
                        .Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
                    if (isPartial == false)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticsDescriptors.KNoPartialKeyworkErrorDescriptor,
                            Location.Create(candidateClass.SyntaxTree, new TextSpan()),
                            typeSymbol.Name));
                        continue;
                    }

                    var @interface = typeSymbol.Interfaces.FirstOrDefault();
                    if (@interface == null)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(
                            DiagnosticsDescriptors.KNoInterfaceErrorDescriptor,
                            Location.Create(candidateClass.SyntaxTree, new TextSpan()),
                            typeSymbol.Name));
                        continue;
                    }

                    var className = typeSymbol.Name;
                    var interfaceName = @interface.Name;
                    var members = @interface.GetMembers();
                    var nameSpace = typeSymbol.ContainingNamespace.ToDisplayString(KNamespaceDisplayFormat);
                    var code = $@"// <auto-generated />
using LightMock;

namespace {nameSpace}
{{
    partial class {className}
    {{
        private readonly IInvocationContext<{interfaceName}> context;

        public {className}(IInvocationContext<{interfaceName}> context)
        {{
            this.context = context;
        }}

        {string.Join("\r\n        ", EnrichMembers(members))}
    }}
}}
";
                    context.AddSource(className + ".g.cs", SourceText.From(code, Encoding.UTF8));
                }
            }
        }

        IEnumerable<string> EnrichMembers(IEnumerable<ISymbol> symbols)
            => symbols.Select(i => EnrichMember(i));

        string EnrichMember(ISymbol symbol) => symbol.Accept(new EnrichSymbolVisitor());

        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => new StaticProxySyntaxReceiver());
        }
    }
}
